/*
  -----------------------------------------------------------------------------
  Proyecto: RuteX Go
  Desarrollado por: TurisTechTeam
  Descripción: Esta aplicación y su código fuente son propiedad intelectual de
  TurisTechTeam. Queda prohibida su copia, distribución o uso no autorizado.
  Año: 2026
  -----------------------------------------------------------------------------
*/
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGwLvBMX6tJ9tSTmvLDTfKC11A9jFtos',
    appId: '1:711545941492:web:48d448bba20abff1041da1',
    messagingSenderId: '711545941492',
    projectId: 'rutexgo-2dama',
    authDomain: 'rutexgo-2dama.firebaseapp.com',
    storageBucket: 'rutexgo-2dama.firebasestorage.app',
    measurementId: 'G-FMCQ9SXYTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLMF2UVlLLnzi20qdSCnGQD39IcDQIK6I',
    appId: '1:711545941492:android:69abe8c325bcb01c041da1',
    messagingSenderId: '711545941492',
    projectId: 'rutexgo-2dama',
    storageBucket: 'rutexgo-2dama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vRaTFKOBn4qUKiW4Sw9PS3LIifFiGjY',
    appId: '1:711545941492:ios:9b99a943917ebe01041da1',
    messagingSenderId: '711545941492',
    projectId: 'rutexgo-2dama',
    storageBucket: 'rutexgo-2dama.firebasestorage.app',
    iosBundleId: 'com.rutexgo.mobileApp',
  );
}
