name: mobile_app
description: "Aplicación móvil gamificada para turismo cultural en Extremadura"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Registro de imágenes y logos de RutexGO
  assets:
    - assets/Mapa Fondo Extremadura.jpeg
    - assets/logos finales rutexgo1.2.png

  # Configuración de la familia de fuente Montserrat
  fonts:
    - family: Montserrat
      fonts:

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400