name: mobile_app
description: "Aplicación móvil gamificada para turismo cultural en Extremadura"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  google_maps_flutter: ^2.15.0
  flutter_joystick: ^0.2.2
  provider: ^6.1.5
  latlong2: ^0.9.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Icono principal (Verde/Color)
  image_path: "assets/RutexGO_color.png"

  # Configuración para Android Adaptativo (Iconos modernos)
  adaptive_icon_background: "#f5f5f5"
  adaptive_icon_foreground: "assets/RutexGO_color.png"

  monochrome_android_icon: "assets/RutexGO_grises.png"

flutter:
  uses-material-design: true

  # Registro de imágenes y logos de RutexGO
  assets:
    - assets/Mapa_Fondo_Extremadura.jpeg
    - assets/Logo_Color_Rutexgo.png
    - assets/Logo_Negro_Rutexgo.png
    - assets/RutexGO_color.png
    - assets/RutexGO_grises.png
    - assets/images_selection/
    - assets/anfiteatro_romano.jpg
    - assets/merida_cotidiana.png
    - assets/merida_monumental.png
    - assets/merida_vidafe.jpg

  # Configuración de la familia de fuente Montserrat
  fonts:
    - family: Montserrat
      fonts:

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400